name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-index:
    name: Build Search Index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 使用 LTS 版本
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build search index
        run: node build-search-index.js

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main' # 只在 push 到 main 分支時才自動 commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(bot): ✨ 自動更新搜尋索引"
          file_pattern: 'search-index.json'

  link-check:
    name: Check Links
    runs-on: ubuntu-latest
    needs: build-and-index # 等待索引建立完成後再執行
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './**/*.html' './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
